#pragma once

#include <stdlib.h>
#include <array>
#include <utility> // std::declval

#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <chrono>
#include <unordered_map>

#include <cstdint> // uint64_t, int_fast32_t
#include <ctime>

#include <string.h> // memcpy


#include "ParseUtil.hpp"
#include "common.hpp"
#include "errors.hpp"

namespace cshort {

    struct ParseContext;
    struct CodeLine;

    #define NODE_TYPE_ID 0x123
    #define TOKEN_TYPE_ID 0x456

    #define COMMON_HEADER \
        int type_id; \
        _NodeBase *parentNode; \
        CodeLine *codeLine; \
        ParseContext *context; \

    #define NODE_HEADER \
        COMMON_HEADER \
        const struct node_vtable *vtable; /* virtual table */ \
        _NodeBase *nextNode; \

    #define TOKEN_HEADER \
        COMMON_HEADER \
        const struct token_vtable *vtable; /* virtual table */ \
        _TokenBase *nextToken; \
        _TokenBase *nextTokenInLine; \
        int foundPos; \
        /* precedingSpaceCount holds number of chars before this node, used for error reporting and code generation. */ \
        /* this reduces memory usage and keeps AST simple by avoid creating additional nodes for all spaces. */ \
        int precedingSpaceCount; \
        void *precedingCommentToken; \
        /* the first linebreak node before the code node generated by tokenizer  */ \
        struct _LineBreakTokenStruct *precedingLineBreakToken; \


    #define SIMPLE_TEXT_CONTENT \
        utf8byte *text; \
        int_fast32_t textLength;


    #define INIT_NODE(node, context, parent, argvtable) \
        (node)->vtable = (argvtable); \
        (node)->type_id = NODE_TYPE_ID; \
        (node)->context = (context); \
        (node)->parentNode = (NodeBase*)(parent); \
        (node)->codeLine = nullptr; \
        (node)->nextNode = nullptr; \
        (0)

    #define INIT_TOKEN(token, context, parent, argvtable) \
        (token)->vtable = (argvtable); \
        (token)->type_id = TOKEN_TYPE_ID; \
        (token)->precedingSpaceCount = 0; \
        (token)->context = (context); \
        (token)->parentNode = (NodeBase*)(parent); \
        (token)->codeLine = nullptr; \
        (token)->foundPos = -1; \
        (token)->nextToken = nullptr; \
        (token)->nextTokenInLine = nullptr; \
        (token)->precedingLineBreakToken = nullptr; \
        (token)->precedingCommentToken = nullptr; \
        (0)

    #define TEXT_MEMCPY(dst, src, len) \
        memcpy((dst), (src), (len))

    using NodeBase = struct _NodeBase {
        NODE_HEADER;
    };

    using TokenBase = struct _TokenBase {
        TOKEN_HEADER;
    };

    using SimpleTextTokenStruct = struct _SimpleTextTokenStruct {
        TOKEN_HEADER;

        SIMPLE_TEXT_CONTENT;
    };

    using KeywordTokenStruct = SimpleTextTokenStruct;


    using LineCommentTokenStruct = SimpleTextTokenStruct;
    using BlockCommentFragmentStruct = SimpleTextTokenStruct;
    using ConstLiteralTokenStruct = SimpleTextTokenStruct; // null, false, true

    // LineBreakTokenStruct is used for storing line break info for error reporting and code generation.
    using LineBreakTokenStruct = struct _LineBreakTokenStruct {
        TOKEN_HEADER;

        utf8byte text[3]; // "\r\n", "\n", "\r" or "\0"
        _LineBreakTokenStruct *nextLineBreak;
    };

    using BlockCommentTokenStruct = struct _BlockCommentTokenStruct {
        TOKEN_HEADER;

        BlockCommentFragmentStruct *firstCommentFragment;
        char* tagText; // for named block comment /*<[hoge] ... [hoge]>*/
        int tagTextLength;
    };


    using EndOfFileNodeStruct = struct _EndOfFileNodeStruct {
        NODE_HEADER;

        SimpleTextTokenStruct eofToken;
    };


    using IdentifierTokenStruct = struct _IdentifierTokenStruct {
        TOKEN_HEADER;

        int stackOffset;
        char *name;
        int_fast32_t nameLength;
    };

    using SymbolTokenStruct = struct _SymbolTokenStruct {
        TOKEN_HEADER;

        bool isEnabled;
        utf8byte symbol[2];
        bool isEndFlag;
    };

    
    using NumberNodeStruct = struct _NumberNodeStruct {
        NODE_HEADER;

        SimpleTextTokenStruct originalNumberTextToken;

        int64_t num;
        int unit;
    };

    // namespace::ClassName.Property
    // namespace::Method() // () excluded, Expression tokenizer will deal with it.
    // localVariable
    using IdentifiersAccessNodeStruct = struct _IdentifiersAccessNodeStruct {
        NODE_HEADER;
        int stackOffset;

        IdentifierTokenStruct identifierToken;
    };

    using ParenthesesNodeStruct = struct _ParenthesesNodeStruct {
        NODE_HEADER;

        SymbolTokenStruct openNode;
        SymbolTokenStruct closeNode;

        NodeBase *valueNode;
    };

    using ClassNodeStruct = struct _ClassNodeStruct {
        NODE_HEADER;

        KeywordTokenStruct classKeywordToken;
        IdentifierTokenStruct identifierToken;

        struct Impl;
        struct Impl *sub;

        bool startFound;

        SymbolTokenStruct bodyStartSymbolToken;
        SymbolTokenStruct endBodySymbolToken;

        NodeBase *firstChildNode;
        NodeBase *lastChildNode;
        int childCount;
    };

    // ?string str
    using TypeNodeStruct = struct _TypeNodeStruct {
        NODE_HEADER;

        SIMPLE_TEXT_CONTENT;

        bool hasImmutableMark; // # immutable
        bool hasNullableMark; // ? nullable
        bool isLet; // or has type

        IdentifierTokenStruct nameNode; // type name like int, string, etc..
        SimpleTextTokenStruct typeTextToken; // including ? or #
    };

    
    using StringLiteralTokenStruct = struct _StringLiteralTokenStruct {
        TOKEN_HEADER;
        char *text; // unparsed text including ""
        int_fast32_t textLength;

        char *str;
        int strLength;

        int literalType; // 0: "text", 1: `text`
    };


    // true, false, null
    using LiteralValueNodeStruct = struct _LiteralValueStruct {
        NODE_HEADER;

        bool isTrue;
        bool isFalse;
        bool isNull;
        bool isStringLiteral;

        ConstLiteralTokenStruct *textToken;
        // if this literal is string, store the string literal node here for code generation.
        StringLiteralTokenStruct *stringLiteralToken;
    };
    

    // int a = 5
    // immutable: #int a = 5
    // nullable: ?let *ptr = "jfwio"
    using AssignStatementNodeStruct = struct _AssignStatementNodeStruct {
        NODE_HEADER;

        TypeNodeStruct typeOrLet; // #let, int, ?string, etc..
        bool hasTypeDecl; // only assignment: a = 3
        SymbolTokenStruct pointerAsterisk; // *

        int stackOffset;
        IdentifierTokenStruct nameNode; // variable name
        SymbolTokenStruct equalSymbol; // =
        NodeBase *expressionNode; // 32
    };

    using KeywordAndExpressionStruct = struct _KeywordAndExpressionStruct {
        NODE_HEADER;

        SimpleTextTokenStruct returnText;
        NodeBase *expressionNode;
    };

    using ReturnStatementNodeStruct = KeywordAndExpressionStruct;



    using FuncBodyNodeStruct = struct _BodyNodeStruct {
        NODE_HEADER;

        bool startFound;
        bool firstStatementFound;

        SymbolTokenStruct bodyStartNode;
        SymbolTokenStruct endBodyNode;

        NodeBase *firstChildNode;
        NodeBase *lastChildNode;
        int childCount;
    };



    // (?int point = null)
    using FuncParameterItemStruct = struct _FuncParameterItemStruct {
        NODE_HEADER;
        AssignStatementNodeStruct *assignStatementNodeStruct;
        SymbolTokenStruct  followingComma;
        bool hasComma;
    };

    using FuncNodeStruct = struct _FuncNodeStruct {
        NODE_HEADER;

        SimpleTextTokenStruct fnKeywordToken; // "fn"
        IdentifierTokenStruct funcNameToken;
        int stackSize;

        SymbolTokenStruct parameterStartNode; // (
        SymbolTokenStruct parameterEndNode; // )

        FuncBodyNodeStruct bodyNode;

        int parameterParsePhase;
        FuncParameterItemStruct *firstChildParameterNode;
        FuncParameterItemStruct *lastChildParameterNode;
        int parameterChildCount;
    };


    using FuncCallArgItemStruct = struct _FuncArgumentItemStruct {
        NODE_HEADER;

        NodeBase *exprNode; // expression Node
        SymbolTokenStruct follwingComma;
        bool hasComma;
    };


    // func(23, "str")
    using FuncCallNodeStruct = struct _FuncCallNodeStruct {
        NODE_HEADER;

        NodeBase *callerExprNode; // this can be a variable or a property access like obj.method, or even a func call like getFunc()()
        int parsePhase;
        SymbolTokenStruct openParenthesisToken;
        SymbolTokenStruct closeParenthesisToken;

        FuncCallArgItemStruct *firstArgumentItem;
        FuncCallArgItemStruct *lastArgumentItem;
    };

    

    enum BinaryOperationGroup {
        Add_Subtract, // +, - 
        Multiply_Divide_Modulo, // *,/,%
        And_Or, // &&, ||
        BitwiseAnd_BitwiseOr, // &, |
    };

    // a + 
    using OpItemNodeStruct = struct _OpItemNodeStruct {
        NodeBase *leftExprNode;
        bool hasFollowingOpToken;
        SymbolTokenStruct opToken; // op can be +, -, *, /, %, etc..
    };

    using BinaryOperationNodeStruct = struct _BinaryOperationNodeStruct {
        NODE_HEADER;

        NodeBase *leftExprNode;
        SymbolTokenStruct opToken; // op can be +, -, *, /, %, etc..
        NodeBase *rightExprNode;
        BinaryOperationGroup opGroup;
    };



    enum DocumentType {
        CodeDocument,
        JsonDocument,// for LSP server
    };

    using DocumentStruct = struct _documentStruct {
        NODE_HEADER;

        DocumentType documentType;
        char *fileName;
        EndOfFileNodeStruct endOfFile;

        int nodeCount{0};

        CodeLine *firstCodeLine;
        int lineCount;

        NodeBase *firstRootNode;
        NodeBase *lastRootNode;
    };


    enum class AppendLineMode {
        Normal,
        DetectErrorSpanTokens // add tokens only on the line that has syntax error, used for LSP server to reduce unnecessary addition.
    };

    class IndentRuleApplier {
private:
    ParseContext *context;
    CodeLine *firstLine;
    CodeLine *currentCodeLine;
    int firstDepth;
    bool firstIncrementMode;
    int endBracketDepth;
    
public:
    IndentRuleApplier(ParseContext *context, CodeLine *currentCodeLine) {
        assert(context != nullptr);
        this->context = context;
        this->currentCodeLine = currentCodeLine;
        this->firstLine = currentCodeLine;
        this->firstDepth = context->currentIndentDepth;
        this->firstIncrementMode = context->incrementDepthOnNextLine;
        int endBracketDepth = context->getNextLineIndentDepth();
        this->endBracketDepth = endBracketDepth;

    }
    
    ~IndentRuleApplier() {
        if (CodeLine::HasOnlyEndParentheses(currentCodeLine)) {
            currentCodeLine->depth = endBracketDepth;
        }
        
        // if the body is empty, the end bracket will be in the same line as the start bracket, in this case we should not change the indent depth for this line, and the indent depth should be the same as the parent node's indent depth.
        if (currentCodeLine == firstLine) {
            context->currentIndentDepth = firstDepth;
            context->incrementDepthOnNextLine = firstIncrementMode;
        }
        else {
            context->currentIndentDepth = endBracketDepth;
        }

    }
    
    // コピー禁止
    IndentRuleApplier(const IndentRuleApplier&) = delete;
    IndentRuleApplier& operator=(const IndentRuleApplier&) = delete;
    
    // ムーブは許可
    IndentRuleApplier(IndentRuleApplier&& other) noexcept {
        this->context = other.context;
        this->firstLine = other.firstLine;
        this->currentCodeLine = other.currentCodeLine;
        this->firstDepth = other.firstDepth;
        this->firstIncrementMode = other.firstIncrementMode;
        this->endBracketDepth = other.endBracketDepth;
        other.context = nullptr;
    }
};

    struct ParseContext {
        st_uint start;
        int length;
        bool scanEnd; // used for tokenizer to indicate the end of scan.
        AppendLineMode appendLineMode; // 0:
        int lastTokenizedPos; // used for error reporting 

        bool isAfterLineBreak; // for loopMode=true tokenizer
        TokenBase *mostLeftToken; // store the most left token generated by tokenizer,
                                // used for assigning line break and comment tokens in scanWithTokenizer
        NodeBase *generatedPrimaryNode; // store the primary node generated by tokenizer, used for dealing with it in caller.
        const utf8byte *chars;

        ClassNodeStruct *unusedClassNode;
        AssignStatementNodeStruct *unusedAssignment;

        LineBreakTokenStruct *remainedLineBreakToken;
        void *remainedCommentToken;
        int remainedSpaceCount{0};

        MemBuffer memBuffer;
        MemBuffer memBufferForCodeLines;

        IndentRuleApplier CreateIndentRuleApplier(CodeLine *currentCodeLine) {
            return IndentRuleApplier(this, currentCodeLine);
        }

        void init() {
            memBuffer.init();
            memBufferForCodeLines.init();
            appendLineMode = AppendLineMode::Normal;
            syntaxErrorInfo.hasError = false;
            syntaxErrorInfo.errorItem.errorIndex = ErrorIndex::no_syntax_error;
            syntaxErrorInfo.errorItem.errorId = 10000;
        }

        void dispose() {
            memBuffer.freeAll();
            memBufferForCodeLines.freeAll();
        }

        template<typename T>
        T *newMem() {
            return (T *) memBuffer.newMem<T>(1);
        }

        template<typename T>
        void tryDelete(T *m) {
            memBuffer.tryDelete(m);
        }

        template<typename T>
        T *newMemArray(st_size len) {
            return (T *) memBuffer.newMem<T>(len);
        }
        utf8byte *newText(st_size len) {
            return memBuffer.newText(len);
        }


        LineBreakTokenStruct *newLineBreakToken() {
            return memBuffer.newMem<LineBreakTokenStruct>(1);
        }

        CodeLine *newCodeLine() {
            return memBufferForCodeLines.newMem<CodeLine>(1);
        }

        template<typename T>
        T *newMemForNode() {
            return memBuffer.newMem<T>(1);
        }


        
        int baseIndent;
        SyntaxErrorInfo syntaxErrorInfo;
        bool has_depth_error{false};
        int currentIndentDepth { -1 };
        bool incrementDepthOnNextLine{false}; // when true, the next line break will increase indent depth by 1.
        int arithmeticBaseDepth{ -1 };

        void setError(ErrorIndex errorCode, st_int startPos) {
            setError2(errorCode, startPos, startPos);
        }

        inline int getNextLineIndentDepth() const {
            return currentIndentDepth + (incrementDepthOnNextLine ? 1 : 0);
        }

        void setError2(ErrorIndex errorCode, st_int startPos, st_int startPos2) {
            if (syntaxErrorInfo.hasError) {
                return;
            }
            syntaxErrorInfo.hasError = true;
            auto &item = syntaxErrorInfo.errorItem;
            item.errorIndex = errorCode;
            item.errorId = getErrorCode(errorCode);
            item.charPosition = startPos;
            item.charPosition2 = startPos2;

            const char *msg = getErrorMessage(errorCode);
            if (msg != nullptr) {
                snprintf(item.reason, MAX_REASON_LENGTH, "%s", msg);
                item.reasonLength = static_cast<int>(strlen(item.reason));
            }
        }

        void setIndentError(ErrorIndex errorCode, st_int line1, st_int charPos1) {
            setError3(errorCode, line1, charPos1, line1, charPos1);
        }

        void setError3(ErrorIndex errorCode, st_int line1, st_int charPos1, st_int line2, st_int charPos2) {
            if (syntaxErrorInfo.hasError) {
                return;
            }
            syntaxErrorInfo.hasError = true;
            auto &item = syntaxErrorInfo.errorItem;
            item.errorIndex = errorCode;
            item.errorId = getErrorCode(errorCode);
            item.linePos1 = line1;
            item.charPos1 = charPos1;
            item.linePos2 = line2;
            item.charPos2 = charPos2;

            const char *msg = getErrorMessage(errorCode);
            if (msg != nullptr) {
                snprintf(item.reason, MAX_REASON_LENGTH, "%s", msg);
                item.reasonLength = static_cast<int>(strlen(item.reason));
            }
        }
    };


    struct Cast {
        template<typename T>
        static inline T downcast(void *node) {
            return (T) node;
        }

        template<typename T>
        static inline NodeBase *upcast(T *node) {
            auto *n =  (NodeBase *) node;
            assert(n->type_id == NODE_TYPE_ID);
            return n;
        }

        template<typename T>
        static inline TokenBase *upcastToken(T *token) {
            auto *t = (TokenBase *) token;
            assert(t->type_id == TOKEN_TYPE_ID);
            return t;
        }
    };

    enum class NodeTypeId {
        Document = 0,
        EndOfDoc = 1,
        Class = 4,
        Func = 17,
        Body = 19,
        Type = 18,
        AssignStatement = 20,
        ReturnStatement = 24,
        Parentheses = 26,
        FuncCall = 27,
        FuncArgument = 28,
        FuncParameter = 29,
        BinaryOperation = 30,
        IdentifiersAccess = 25,
        FixedLiteral = 31,
        Number = 32,
    };

    enum class TokenTypeId {

        StringLiteral = 2,
        Symbol = 3,
        Identifier = 5,
        SimpleText = 6,

        Number = 9,
        LineBreak = 10,
        Bool = 11,
        ConstLiteral = 12,
        
        NULLId = 16,
        
        LineComment = 21,
        BlockComment = 22,
        BlockCommentFragment = 23,
    };



    #define ApplyFunc_params3 \
        void *scriptEngineContext, \
        void *targetVTable, \
        int (*func)(NodeBase *, void *scriptEngineContext, void *targetVTable,void *func, bool parentIsFirst, void *arg, void *arg2), \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2

    #define TokenApplyFunc_params3 \
        void *scriptEngineContext, \
        void *targetVTable, \
        int (*func)(TokenBase *, void *scriptEngineContext, void *targetVTable,void *func, bool parentIsFirst, void *arg, void *arg2), \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2


    #define ApplyFunc_params2 \
        void *scriptEngineContext, \
        void *targetVTable, \
        void *func, \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2


    #define ApplyFunc_pass \
                scriptEngineContext, \
                targetVTable, (void *)func, parentIsFirst, topLevelNodeInBody, arg2

    #define ApplyFunc_pass2 \
                scriptEngineContext, \
                targetVTable, func, parentIsFirst, topLevelNodeInBody, arg2


    #define NODE_VTABLE_DEF(T) \
        int (*selfTextLength)(T *self); \
        /* no need to add null terminator, caller will add it using selfTextLength() */ \
        void (*copySelfText)(T *self, utf8byte *buf); \
        CodeLine *(*appendToLine)(T *self, CodeLine *line); \
        int (*applyFuncToDescendants)(T *Node, ApplyFunc_params3); \
        const char *typeChars; \
        int typeCharsLength; \
        int (*typeSelector)(void *env, NodeBase *self);     \
        NodeTypeId nodeTypeId; \

    #define TOKEN_VTABLE_DEF(T) \
        int (*selfTextLength)(T *self); \
        /* no need to add null terminator, caller will add it using selfTextLength() */ \
        void (*copySelfText)(T *self, utf8byte *buf); \
        CodeLine *(*appendToLine)(T *self, CodeLine *line); \
        int (*applyFuncToDescendants)(T *Node, TokenApplyFunc_params3); \
        const char *typeChars; \
        int typeCharsLength; \
        int (*typeSelector)(void *env, NodeBase *self);     \
        TokenTypeId nodeTypeId; \


    /**
     * Node vtable
     */
    using NodeVTable = struct node_vtable {
        NODE_VTABLE_DEF(NodeBase)
    };

    /**
     * token vtable
     */
    using TokenVTable = struct token_vtable {
        TOKEN_VTABLE_DEF(TokenBase)
    };



    // this is for static type checking
    template<typename T>
    struct nodeVirtualTable {
        NODE_VTABLE_DEF(T)
    };

    template<typename T>
    struct tokenVirtualTable {
        TOKEN_VTABLE_DEF(T)
    };


    using selfTextLengthFunction = decltype(std::declval<NodeVTable>().selfTextLength);
    using selfTextFunction = decltype(std::declval<NodeVTable>().copySelfText);
    using appendToLineFunction = decltype(std::declval<NodeVTable>().appendToLine);
    using applyFuncToDescendantsFunction = decltype(std::declval<NodeVTable>().applyFuncToDescendants);

    template<typename T, std::size_t SIZE>
    static int vtable_type_check(
            decltype(std::declval<nodeVirtualTable<T>>().selfTextLength) f1,
            decltype(std::declval<nodeVirtualTable<T>>().copySelfText) f2,
            decltype(std::declval<nodeVirtualTable<T>>().appendToLine) f3,
            decltype(std::declval<nodeVirtualTable<T>>().applyFuncToDescendants) f4,
            const char(&f5)[SIZE],
            NodeTypeId f6
    ) noexcept {
        return 0;
    }



    #define CREATE_VTABLE(T, f1, f2, f3, f4, f5, f6) \
        node_vtable { \
            reinterpret_cast<selfTextLengthFunction> (f1) \
            , reinterpret_cast<selfTextFunction> (f2) \
            , reinterpret_cast<appendToLineFunction> (f3) \
            , reinterpret_cast<applyFuncToDescendantsFunction> (f4) \
            , (const char *)(f5) \
            , (sizeof(f5)-1) \
            , nullptr \
            , f6 \
        } \
        ;static const int check_result_##T = vtable_type_check<T>(f1,f2,f3,f4,f5,f6)

    
    using token_selfTextLengthFunction = decltype(std::declval<TokenVTable>().selfTextLength);
    using token_selfTextFunction = decltype(std::declval<TokenVTable>().copySelfText);
    using token_appendToLineFunction = decltype(std::declval<TokenVTable>().appendToLine);
    using token_applyFuncToDescendantsFunction = decltype(std::declval<TokenVTable>().applyFuncToDescendants);

    template<typename T, std::size_t SIZE>
    static int token_vtable_type_check(
        decltype(std::declval<tokenVirtualTable<T>>().selfTextLength) f1,
        decltype(std::declval<tokenVirtualTable<T>>().copySelfText) f2,
        decltype(std::declval<tokenVirtualTable<T>>().appendToLine) f3,
        decltype(std::declval<tokenVirtualTable<T>>().applyFuncToDescendants) f4,
        const char(&f5)[SIZE],
        TokenTypeId f6
    ) noexcept {
        return 0;
    }

    #define CREATE_TOKEN_VTABLE(T, f1, f2, f3, f4, f5, f6) \
        token_vtable { \
            reinterpret_cast<token_selfTextLengthFunction> (f1) \
            , reinterpret_cast<token_selfTextFunction> (f2) \
            , reinterpret_cast<token_appendToLineFunction> (f3) \
            , reinterpret_cast<token_applyFuncToDescendantsFunction> (f4) \
            , (const char *)(f5) \
            , (sizeof(f5)-1) \
            , nullptr \
            , f6 \
        } \
        ;static const int check_result_##T = token_vtable_type_check<T>(f1,f2,f3,f4,f5,f6)


    struct VTables {
        static const node_vtable
                *DocumentVTable,
                *ClassVTable,
                *FuncDefVTable,
                *FuncBodyVTable,
                *EndOfFileVTable,
                *FuncParameterVTable,
                *AssignStatementVTable,
                *ReturnStatementVTable,
                *TypeVTable,
                *FixedLiteralVTable,
                *NumberVTable,
                *ParenthesesVTable,
                *IdentifiersAccessVTable,
                *FuncCallArgVTable,
                *FuncCallVTable,
                *BinaryOperationVTable
                ;

        static const token_vtable
                *ConstLiteralVTable,     
                *LineBreakVTable,
                *LineCommentVTable,
                *BlockCommentFragmentVTable,
                *SimpleTextVTable,
                *BlockCommentVTable,
                *IdentifierTokenVTable,
                *StringLiteralTokenVTable,
                *SymbolTokenVTable,
                *LineBreakTokenVTable
                ;
    };




    struct VTableCall {

        static int selfTextLength(NodeBase *node) {
            assert(node);
            assert(node->vtable);
            assert(node->vtable->selfTextLength);

            return node->vtable->selfTextLength(node);
        }


        static inline void copySelfText(void *node, char *buf) {
            if (node == nullptr) {
                return;
            } else {
                auto *nodeBase = Cast::upcast(node);
                nodeBase->vtable->copySelfText(nodeBase, buf);
            }
        }

        static int typeTextLength(NodeBase *node) {
            assert(node);
            assert(node->vtable);
            return node->vtable->typeCharsLength;
        }


        static inline const utf8byte *typeText(void *node) {
            if (node == nullptr) {
                return "";
            } else {
                auto *nodeBase = Cast::upcast(node);
                return nodeBase->vtable->typeChars;
            }
        }


        // forward declaration of functions in parser_core.cpp to avoid circular dependency 
        static inline CodeLine *callAppendNodeToLine(void *node, CodeLine *currentCodeLine) {
            if (node == nullptr) { // BreakLineToken can be null
                return currentCodeLine;
            }
            auto *nodeBase = Cast::upcast(node);
            assert(nodeBase->type_id == NODE_TYPE_ID);

            return nodeBase->vtable->appendToLine(nodeBase, currentCodeLine);
        }
    };

    struct TokenVTableCall {

        static int selfTextLength(TokenBase *token) {
            assert(token);
            assert(token->vtable);
            assert(token->vtable->selfTextLength);

            return token->vtable->selfTextLength(token);
        }

        static inline void copySelfText(void *token, char *buf) {
            if (token == nullptr) {
                return;
            } else {
                auto *tokenBase = Cast::upcastToken(token);
                tokenBase->vtable->copySelfText(tokenBase, buf);
            }
        }

        static int typeTextLength(TokenBase *token) {
            assert(token);
            assert(token->vtable);
            return token->vtable->typeCharsLength;
        }

        static inline const utf8byte *typeText(void *token) {
            if (token == nullptr) {
                return "";
            } else {
                auto *tokenBase = Cast::upcastToken(token);
                return tokenBase->vtable->typeChars;
            }
        }

        // forward declaration of functions in parser_core.cpp to avoid circular dependency 
        static inline CodeLine *callAppendTokenToLine(void *token, CodeLine *currentCodeLine) {
            if (token == nullptr) { // BreakLineToken can be null
                return currentCodeLine;
            }

            auto *tokenBase = Cast::upcastToken(token);
            assert(tokenBase->type_id == TOKEN_TYPE_ID);
            if (tokenBase->foundPos < 0) {
                printf("no foundPos > -1: %s\n", typeText(tokenBase));
            }
            assert(tokenBase->foundPos >= 0);

            // if the token has precedingLineBreakToken, append the precedingLineBreakToken before appending the token itself,
            // so that the line break will be before the token in the code line,
            // which is more intuitive and easier to handle when generating code later
            return tokenBase->vtable->appendToLine(tokenBase, currentCodeLine);
        }
    };

    struct CodeLine {
        CodeLine *nextLine;
        int lineNumber;
        //CodeLine *prev;
        TokenBase *firstToken;
        TokenBase *lastToken;
        // int indent;
        ParseContext *context;

        int depth;

        void init(ParseContext *argContext) {
            this->context = argContext;
            this->lineNumber = 0;

            this->firstToken = nullptr;
            this->lastToken = nullptr;
            this->nextLine = nullptr;
            ///this->prev = nullptr;
            this->depth = 0;
        }

        static inline bool HasOnlyEndParentheses(CodeLine *line) {
            auto token = line->firstToken;
            while (token != nullptr) {
                auto currentToken = token;
                token = token->nextTokenInLine; // assign next token before checking current token

                printf("currentToken: %s\n", TokenVTableCall::typeText(currentToken));
                if (currentToken->vtable == VTables::BlockCommentFragmentVTable
                     || currentToken->vtable == VTables::BlockCommentVTable) {
                    continue;
                }

                if (currentToken->vtable != VTables::SymbolTokenVTable) {
                    return false;
                }

                auto *symbolToken = Cast::downcast<SymbolTokenStruct *>(currentToken);
                if (!symbolToken->isEndFlag) {
                    return false;
                }
            }
            return true;
        }
        // insert token into this line, if prev is null, insert it into top of the line
        CodeLine *insertToken(TokenBase *token, TokenBase *prev) {
            if (firstToken == nullptr) {
                assert(prev == nullptr);
                firstToken = token;
                lastToken = token;
            } else {
                if (prev != nullptr) { // insert it after prev
                    token->nextTokenInLine = prev->nextTokenInLine;
                    prev->nextTokenInLine = token;
                    if (prev == lastToken) {
                        lastToken = (TokenBase *) token;
                    }
                } else { // insert into top
                    (token)->nextTokenInLine = firstToken;
                    firstToken = token;
                }
            }

            ((TokenBase *) token)->codeLine = this;

            return this;
        }

        // append token to the end of the line
        CodeLine *appendToken(void *token) {
            if (firstToken == nullptr) {
                firstToken = (TokenBase *) token;
            }

            if (lastToken != nullptr) {
                if (this->context->appendLineMode == AppendLineMode::Normal) {
                    lastToken->nextTokenInLine = (TokenBase *) token;
                }
            }

            lastToken = (TokenBase *) token;
            assert(lastToken->type_id == TOKEN_TYPE_ID);
            assert(lastToken->parentNode != nullptr);
            if (this->context->appendLineMode == AppendLineMode::Normal) {
                ((TokenBase *) token)->codeLine = this;
            }

            return this;
        }

        // when a token is added to a line, there may be some format tokens like comments/line-breaks, so we need to handle them and attach them to the line as well.
        // New CodeLines will be generated during handling LineBreakTokens, and they will be attached to the last line.
        CodeLine *AddAttachedFormatTokens(void *token) {
            CodeLine *currentCodeLine = this;

            if (this->context->appendLineMode == AppendLineMode::Normal) {
                currentCodeLine = TokenVTableCall::callAppendTokenToLine(((TokenBase *) token)->precedingLineBreakToken, currentCodeLine);
            }

            currentCodeLine = TokenVTableCall::callAppendTokenToLine(((TokenBase *) token)->precedingCommentToken, currentCodeLine);

            return currentCodeLine;
        }
    };


    /**
     * Node Changed Event
     */
    enum EventType {
        CreateDocument,
        FirstLineChanged,
        CreateNode,
        CreateLine,
    };

    /**
     * Defines Managed Coding Operations
     */
    enum class CodingOperations {
        AutoIndentSelection,
        AutoIndentForSpacingRule,
        BreakLine,
        Deletion,
        //AddMapItem
    };

    struct OperationResult {

    };

    struct DocumentUtils {
        static void parseText(DocumentStruct *docStruct, const utf8byte *text, int length);

        static void regenerateCodeLines(DocumentStruct *docStruct);

        static utf8byte *getTextFromTree(DocumentStruct *doc);
    };


    struct Init {
        // Nodes
        static void initFuncBodyNode(FuncBodyNodeStruct *node, ParseContext *context, void *parentNode);
        static void initTypeNode(TypeNodeStruct *self, ParseContext *context, void *parent);

        static void initAssignStatement(ParseContext *context, NodeBase *parentNode,
                                       AssignStatementNodeStruct *assignStatement
        );

        static void initReturnStatement(ParseContext *context, NodeBase *parentNode,
                                        ReturnStatementNodeStruct *returnStatement
        );
        // Tokens
        static void initIdentifierToken(IdentifierTokenStruct *name, ParseContext *context, void *parentNode);

        static void initSymbolToken(SymbolTokenStruct *self, ParseContext *context, void *parent, utf8byte letter);

        static void initSimpleTextToken(SimpleTextTokenStruct *textToken, ParseContext *context, void *parentNode, int charLen);
        static void assignText_SimpleTextToken(SimpleTextTokenStruct *textToken, ParseContext *context, const utf8byte *text, int charLen);
        static void initStringLiteralNode(StringLiteralTokenStruct *name, ParseContext *context,
                                          NodeBase *parentNode);

    };


    struct Alloc {

        // Tokens
        static LineBreakTokenStruct *newLineBreakToken(ParseContext *context, void *parentNode);
        static SimpleTextTokenStruct *newSimpleTextToken(ParseContext *context, NodeBase *parentNode);

        static LineCommentTokenStruct *newLineCommentToken(ParseContext *context, void *parentNode);
        static BlockCommentTokenStruct *newBlockCommentToken(ParseContext *context, void *parentNode);
        static BlockCommentFragmentStruct *newBlockCommentFragmentToken(ParseContext *context, BlockCommentTokenStruct *parentNode);
        static ConstLiteralTokenStruct *newConstLiteralToken(ParseContext *context, NodeBase *parentNode);
        static StringLiteralTokenStruct *newStringLiteralToken(ParseContext *context, NodeBase *parentNode);

        // Nodes
        static ClassNodeStruct *newClassNode(ParseContext *context, NodeBase *parentNode);
        static LiteralValueNodeStruct *newLiteralValueNode(ParseContext *context, NodeBase *parentNode);
        static NumberNodeStruct *newNumberNode(ParseContext *context, NodeBase *parentNode);

        static DocumentStruct *newDocument(DocumentType docType);
        static void deleteDocument(DocumentStruct *doc);

        static TypeNodeStruct *newTypeNode(ParseContext *context, NodeBase *parentNode);

        static AssignStatementNodeStruct *newAssignStatement(ParseContext *context, NodeBase *parentNode);
        static ReturnStatementNodeStruct *newReturnStatement(ParseContext *context, NodeBase *parentNode);

        static FuncNodeStruct *newFuncNode(ParseContext *context, NodeBase *parentNode);

        static FuncParameterItemStruct *newFuncParameterItem(ParseContext *context, NodeBase *parentNode);

        static ParenthesesNodeStruct *newParenthesesNode(ParseContext *context, NodeBase *parentNode);
        static IdentifiersAccessNodeStruct *newIdentifiersAccessNode(ParseContext *context, NodeBase *parentNode);

        static FuncCallArgItemStruct *newFuncCallArgItem(ParseContext *context, NodeBase *parentNode);
        static FuncCallNodeStruct *newFuncCallNode(ParseContext *context, NodeBase *parentNode);

        // operations
        static BinaryOperationNodeStruct *newBinaryOperationNode(ParseContext *context, NodeBase *parentNode, char op);

    };




    /**
     * Function Types and vtable for node structures
     */
    #define TokenizerParams_argNode_ch_start_context \
        void *argNode, utf8byte ch, st_int start, ParseContext *context


    #define TokenizerParams_pass argNode, ch, start, context
    #define TokenizerParams_pass_3 ch, start, context

    using TokenizerFunction = int (*)(TokenizerParams_argNode_ch_start_context);

    struct NodeUtil {
        static inline bool isEndOfFileToken(TokenBase *token) {
            return token != nullptr
                   && token->parentNode != nullptr
                   && ((NodeBase*)(token->parentNode))->vtable->nodeTypeId == NodeTypeId::EndOfDoc;

        }
    };
    struct Tokenizers {
        // Tokens
        static int identifierTokenizer(TokenizerParams_argNode_ch_start_context);
        static int stringLiteralTokenizer(TokenizerParams_argNode_ch_start_context);

        // Nodes
        static int classTokenizer(TokenizerParams_argNode_ch_start_context);
        static int tokenizeExpression(TokenizerParams_argNode_ch_start_context);
        static int typeTokenizer(TokenizerParams_argNode_ch_start_context);

        static int fixedLiteralNodeTokenizer(TokenizerParams_argNode_ch_start_context);
        static int numberNodeTokenizer(TokenizerParams_argNode_ch_start_context);

        static int bodyTokenizer(TokenizerParams_argNode_ch_start_context);
        static int fnTokenizer(TokenizerParams_argNode_ch_start_context);

        static int assignStatementTokenizer(TokenizerParams_argNode_ch_start_context);
        static int assignStatementWithoutLetTokenizer(TokenizerParams_argNode_ch_start_context);
        static int returnStatementTokenizer(TokenizerParams_argNode_ch_start_context);
        static int parenthesesTokenizer(TokenizerParams_argNode_ch_start_context);
        static int identifiersAccessTokenizer(TokenizerParams_argNode_ch_start_context);

        static int tokenizeFuncCall(TokenizerParams_argNode_ch_start_context);
        static int binaryOperationTokenizer(TokenizerParams_argNode_ch_start_context);

        // tokenizer for simple keywords or symbols, like "null", "true", "false", " ", etc... they can be tokenized in one step without backtracking, so we can use this template function to generate them.
        // generator is a function pointer for generating corresponding token, it will be called when the word is matched, and the generated token will be returned by the tokenizer.
        template<typename TYPE, std::size_t SIZE, typename GENTYPE>
        static inline int tokenizeWord(TokenizerParams_argNode_ch_start_context
                      , GENTYPE* (*generator)(ParseContext *, NodeBase*)
                      , utf8byte capitalLetter
                      , const TYPE(&word)[SIZE])
        {
            if (capitalLetter == ch) {
                int length = st_size_of(word) - 1;
                if (ParseUtil::matchWordWithTerminatableEnd(context->chars, context->length, start, word)) {
                    auto *token = (SimpleTextTokenStruct*)(generator(context, Cast::downcast<NodeBase*>(argNode)));

                    token->foundPos = start;
                    token->text = context->memBuffer.newText(length);
                    token->textLength = length;

                    TEXT_MEMCPY(token->text, context->chars + start, length);
                    token->text[length] = '\0';

                    context->mostLeftToken = Cast::upcastToken(token);
                    return start + length;
                }
            }

            return Search::NOTFOUND;
        }

        // SimpleTextNodeStruct
        template<typename TYPE, std::size_t SIZE>
        static inline int WordTokenizer(TokenizerParams_argNode_ch_start_context
                , utf8byte capitalLetter
                , const TYPE(&word)[SIZE])
        {
            return tokenizeWord(TokenizerParams_pass, Alloc::newSimpleTextToken, capitalLetter, word);
        }
    };


    /**
     * Implements common scanning and parsing method
     */
    struct Scanner {
        static int scanRoot(void *parentNode, TokenizerFunction tokenizer, ParseContext *context);

        static int scanOnce(void *parentNode, TokenizerFunction tokenizer, ParseContext *context, int start);

        static int scanLoop(void *parentNode, TokenizerFunction tokenizer, ParseContext *context, int start);
    };
}