#pragma once

#include <stdlib.h>
#include <array>
#include <utility> // std::declval

#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <chrono>
#include <unordered_map>

#include <cstdint> // uint64_t, int_fast32_t
#include <ctime>

#include <string.h> // memcpy


#include "ParseUtil.hpp"
#include "common.hpp"
#include "errors.hpp"

namespace cshort {

    struct ParseContext;
    struct CodeLine;

    #define NODE_HEADER \
        const struct node_vtable *vtable; /* virtual table */ \
        _NodeBase *parentNode; \
        _NodeBase *nextNode; \
        _NodeBase *nextNodeInLine; \
        CodeLine *codeLine; \
        ParseContext *context; \
        int foundPos; \
        /* precedingSpaceCount holds number of chars before this node, used for error reporting and code generation. */ \
        /* this reduces memory usage and keeps AST simple by avoid creating additional nodes for all spaces. */ \
        int precedingSpaceCount; \
        void *precedingCommentNode; \
        /* the first linebreak node before the code node generated by tokenizer  */ \
        struct _LineBreakNodeStruct *precedingLineBreakNode; \

    #define SIMPLE_TEXT_CONTENT \
        utf8byte *text; \
        int_fast32_t textLength;


    #define INIT_NODE(node, context, parent, argvtable) \
        (node)->vtable = (argvtable); \
        (node)->precedingSpaceCount = 0; \
        (node)->context = (context); \
        (node)->parentNode = (NodeBase*)(parent); \
        (node)->codeLine = nullptr; \
        (node)->foundPos = -1; \
        (node)->nextNode = nullptr; \
        (node)->nextNodeInLine = nullptr; \
        (node)->precedingLineBreakNode = nullptr; \
        (node)->precedingCommentNode = nullptr; \
        (0)

    #define TEXT_MEMCPY(dst, src, len) \
        memcpy((dst), (src), (len))

    using NodeBase = struct _NodeBase {
        NODE_HEADER;
    };


    using SimpleTextNodeStruct = struct _SimpleTextNodeStruct {
        NODE_HEADER;

        SIMPLE_TEXT_CONTENT;
    };

    using LineCommentNodeStruct = SimpleTextNodeStruct;
    using BlockCommentFragmentStruct = SimpleTextNodeStruct;

    // LineBreakNodeStruct is used for storing line break info for error reporting and code generation.
    // This node is not part of main AST, they are attached to code nodes as precedingLineBreakNode.
    // this node also inherits NODE_HEADER because it can be added to CodeLine and have another comments and spaces before it.
    using LineBreakNodeStruct = struct _LineBreakNodeStruct {
        NODE_HEADER;

        utf8byte text[3]; // "\r\n", "\n", "\r" or "\0"
        _LineBreakNodeStruct *nextLineBreakNode;
    };

    using BlockCommentNodeStruct = struct _BlockCommentNodeStruct {
        NODE_HEADER;

        BlockCommentFragmentStruct *firstCommentFragment;
        char* tagText; // for named block comment /*[hoge] ... [hoge]*/
        int tagTextLength;
    };


    using EndOfFileNodeStruct = struct _EndOfFileNodeStruct {
        NODE_HEADER;
    };


    using NameNodeStruct = struct _NameNodeStruct {
        NODE_HEADER;

        int stackOffset;
        char *name;
        int_fast32_t nameLength;
    };

    using SymbolStruct = struct _SymbolStruct {
        NODE_HEADER;

        bool isEnabled;
        utf8byte symbol[2];
    };


    using ClassNodeStruct = struct _ClassNodeStruct {
        NODE_HEADER;

        NameNodeStruct nameNode;

        struct Impl;
        struct Impl *sub;

        bool startFound;
        // utf8byte body[2];

        SymbolStruct bodyStartNode;
        SymbolStruct endBodyNode;

        NodeBase *firstChildNode;
        NodeBase *lastChildNode;
        int childCount;
    };


    enum DocumentType {
        CodeDocument,
        JsonDocument,// for LSP server
    };

    using DocumentStruct = struct _documentStruct {
        NODE_HEADER;

        DocumentType documentType;
        char *fileName;
        EndOfFileNodeStruct endOfFile;

        int nodeCount{0};

        CodeLine *firstCodeLine;
        int lineCount;

        NodeBase *firstRootNode;
        NodeBase *lastRootNode;
    };


    enum class AppendLineMode {
        Normal,
        DetectErrorSpanNodes // add nodes only on the line that has syntax error, used for LSP server to reduce unnecessary addition.
    };

    struct ParseContext {
        st_uint start;
        int length;
        bool scanEnd; // used for tokenizer to indicate the end of scan.
        AppendLineMode appendLineMode; // 0:
        int lastTokenizedPos; // used for error reporting 

        bool isAfterLineBreak; // for loopMode=true tokenizer
        NodeBase *mostLeftNode; // store the most left node generated by tokenizer,
                                // used for assigning line break and comment nodes in scanWithTokenizer
        NodeBase *generatedPrimaryNode; // store the primary node generated by tokenizer, used for dealing with it in caller.
        utf8byte *chars;

        // node caches
        ClassNodeStruct *unusedClassNode;

        LineBreakNodeStruct *remainedLineBreakNode;
        void *remainedCommentNode;
        int remainedSpaceCount{0};

        MemBuffer memBuffer;
        MemBuffer memBufferForCodeLines;

        // set generated node and most left node at the same time.
        void setCodeNode(void* node) {
            this->mostLeftNode = static_cast<NodeBase *>(node);
            this->generatedPrimaryNode = static_cast<NodeBase *>(node);
        }

        void init() {
            memBuffer.init();
            memBufferForCodeLines.init();
            appendLineMode = AppendLineMode::Normal;
            syntaxErrorInfo.hasError = false;
            syntaxErrorInfo.errorItem.errorIndex = ErrorIndex::no_syntax_error;
            syntaxErrorInfo.errorItem.errorId = 10000;
        }

        void dispose() {
            memBuffer.freeAll();
            memBufferForCodeLines.freeAll();
        }

        template<typename T>
        T *newMem() {
            return (T *) memBuffer.newMem<T>(1);
        }

        template<typename T>
        void tryDelete(T *m) {
            memBuffer.tryDelete(m);
        }

        template<typename T>
        T *newMemArray(st_size len) {
            return (T *) memBuffer.newMem<T>(len);
        }
        utf8byte *newText(st_size len) {
            return memBuffer.newText(len);
        }


        LineBreakNodeStruct *newLineBreakNode() {
            return memBuffer.newMem<LineBreakNodeStruct>(1);
        }

        CodeLine *newCodeLine() {
            return memBufferForCodeLines.newMem<CodeLine>(1);
        }

        template<typename T>
        T *newMemForNode() {
            return memBuffer.newMem<T>(1);
        }


        
        int baseIndent;
        SyntaxErrorInfo syntaxErrorInfo;
        bool has_depth_error{false};
        int parentDepth { -1 };
        int arithmeticBaseDepth{ -1 };

        void setError(ErrorIndex errorCode, st_int startPos) {
            setError2(errorCode, startPos, startPos);
        }

        void setError2(ErrorIndex errorCode, st_int startPos, st_int startPos2) {
            if (syntaxErrorInfo.hasError) {
                return;
            }
            syntaxErrorInfo.hasError = true;
            auto &item = syntaxErrorInfo.errorItem;
            item.errorIndex = errorCode;
            item.errorId = getErrorCode(errorCode);
            item.charPosition = startPos;
            item.charPosition2 = startPos2;

            const char *msg = getErrorMessage(errorCode);
            if (msg != nullptr) {
                snprintf(item.reason, MAX_REASON_LENGTH, "%s", msg);
                item.reasonLength = static_cast<int>(strlen(item.reason));
            }
        }

        void setIndentError(ErrorIndex errorCode, st_int line1, st_int charPos1) {
            setError3(errorCode, line1, charPos1, line1, charPos1);
        }

        void setError3(ErrorIndex errorCode, st_int line1, st_int charPos1, st_int line2, st_int charPos2) {
            if (syntaxErrorInfo.hasError) {
                return;
            }
            syntaxErrorInfo.hasError = true;
            auto &item = syntaxErrorInfo.errorItem;
            item.errorIndex = errorCode;
            item.errorId = getErrorCode(errorCode);
            item.linePos1 = line1;
            item.charPos1 = charPos1;
            item.linePos2 = line2;
            item.charPos2 = charPos2;

            const char *msg = getErrorMessage(errorCode);
            if (msg != nullptr) {
                snprintf(item.reason, MAX_REASON_LENGTH, "%s", msg);
                item.reasonLength = static_cast<int>(strlen(item.reason));
            }
        }
    };


    struct Cast {
        template<typename T>
        static inline T downcast(void *node) {
            return (T) node;
        }

        template<typename T>
        static inline NodeBase *upcast(T *node) {
            return (NodeBase *) node;
        }
    };

    enum class NodeTypeId {
        Document = 0,
        EndOfDoc = 1,
        StringLiteral = 2,
        Symbol = 3,
        Class = 4,
        Name = 5,
        SimpleText = 6,

        Number = 9,
        LineBreak = 10,
        Bool = 11,
        
        Func = 17,
        NULLId = 16,

        Type = 18,
        Body = 19,
        AssignStatement = 20,
        ReturnStatement = 24,

        LineComment = 21,
        BlockComment = 22,
        BlockCommentFragment = 23,

        Variable = 25,
        Parentheses = 26,
        FuncCall = 27,
        FuncArgument = 28,
        FuncParameter = 29,

        BinaryOperation = 30
    };



    #define ApplyFunc_params3 \
        void *scriptEngineContext, \
        void *targetVTable, \
        int (*func)(NodeBase *, void *scriptEngineContext, void *targetVTable,void *func, bool parentIsFirst, void *arg, void *arg2), \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2

    #define ApplyFunc_params2 \
        void *scriptEngineContext, \
        void *targetVTable, \
        void *func, \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2


    #define ApplyFunc_pass \
                scriptEngineContext, \
                targetVTable, (void *)func, parentIsFirst, topLevelNodeInBody, arg2

    #define ApplyFunc_pass2 \
                scriptEngineContext, \
                targetVTable, func, parentIsFirst, topLevelNodeInBody, arg2


    #define VTABLE_DEF(T) \
        int (*selfTextLength)(T *self); \
        /* no need to add null terminator, caller will add it using selfTextLength() */ \
        void (*copySelfText)(T *self, utf8byte *buf); \
        CodeLine *(*appendToLine)(T *self, CodeLine *line); \
        int (*applyFuncToDescendants)(T *Node, ApplyFunc_params3); \
        const char *typeChars; \
        int typeCharsLength; \
        int (*typeSelector)(void *env, NodeBase *self);     \
        NodeTypeId nodeTypeId; \


    /**
     * code node vtable
     */
    using NodeVTable = struct node_vtable {
        VTABLE_DEF(NodeBase)
    };



    // this is for static type checking
    template<typename T>
    struct vtableT {
        VTABLE_DEF(T)
    };

    using selfTextLengthFunction = decltype(std::declval<NodeVTable>().selfTextLength);
    using selfTextFunction = decltype(std::declval<NodeVTable>().copySelfText);
    using appendToLineFunction = decltype(std::declval<NodeVTable>().appendToLine);
    using applyFuncToDescendantsFunction = decltype(std::declval<NodeVTable>().applyFuncToDescendants);

    template<typename T, std::size_t SIZE>
    static int vtable_type_check(
            decltype(std::declval<vtableT<T>>().selfTextLength) f1,
            decltype(std::declval<vtableT<T>>().copySelfText) f2,
            decltype(std::declval<vtableT<T>>().appendToLine) f3,
            decltype(std::declval<vtableT<T>>().applyFuncToDescendants) f4,
            const char(&f5)[SIZE],
            NodeTypeId f6
    ) noexcept {
        return 0;
    }
    #define CREATE_VTABLE(T, f1, f2, f3, f4, f5, f6) \
        node_vtable { \
            reinterpret_cast<selfTextLengthFunction> (f1) \
            , reinterpret_cast<selfTextFunction> (f2) \
            , reinterpret_cast<appendToLineFunction> (f3) \
            , reinterpret_cast<applyFuncToDescendantsFunction> (f4) \
            , (const char *)(f5) \
            , (sizeof(f5)-1) \
            , nullptr \
            , f6 \
        } \
        ;static const int check_result_##T = vtable_type_check<T>(f1,f2,f3,f4,f5,f6)

    struct VTables {
        static const node_vtable
                *DocumentVTable,

                *ClassVTable,
                *NameVTable,
                *SymbolVTable,
                *SimpleTextVTable,
                *LineBreakVTable,

                *LineCommentVTable,
                *BlockCommentVTable,
                *BlockCommentFragmentVTable,

                *EndOfFileVTable;
    };




    struct VTableCall {

        static int selfTextLength(NodeBase *node) {
            assert(node);
            assert(node->vtable);
            assert(node->vtable->selfTextLength);

            return node->vtable->selfTextLength(node);
        }


        static inline void copySelfText(void *node, char *buf) {
            if (node == nullptr) {
                return;
            } else {
                auto *nodeBase = Cast::upcast(node);
                nodeBase->vtable->copySelfText(nodeBase, buf);
            }
        }

        static int typeTextLength(NodeBase *node) {
            assert(node);
            assert(node->vtable);
            return node->vtable->typeCharsLength;
        }


        static inline const utf8byte *typeText(void *node) {
            if (node == nullptr) {
                return "";
            } else {
                auto *nodeBase = Cast::upcast(node);
                return nodeBase->vtable->typeChars;
            }
        }


        static CodeLine *callAppendToLine(void *node, CodeLine *currentCodeLine);

    };

    // Generally AST keeps only nodes for executing, they usually exclude spaces, parentheses etc....
    // but in our system, in order to develop dedicated UI for coding, AST-nodes should preserve code formats like spaces/comments/line-breaks.
    // even after editing a code part in CodeLine, there's need to output entire file code with formats.
    // To achive it, we let AST-nodes have spaces/comments/line-breaks information.
    // and We build CodeLine list from AST nodes.
    struct CodeLine {
        CodeLine *nextLine;
        int lineNumber;
        //CodeLine *prev;
        NodeBase *firstNode;
        NodeBase *lastNode;
        // int indent;
        ParseContext *context;

        int depth;

        void init(ParseContext *argContext) {
            this->context = argContext;
            this->lineNumber = 0;

            this->firstNode = nullptr;
            this->lastNode = nullptr;
            this->nextLine = nullptr;
            ///this->prev = nullptr;
            this->depth = 0;
        }

        // insert node into this line, if prev is null, insert it into top of the line
        CodeLine *insertNode(NodeBase *node, NodeBase *prev) {
            if (firstNode == nullptr) {
                assert(prev == nullptr);
                firstNode = node;
                lastNode = node;
            } else {
                if (prev != nullptr) { // insert it after prev
                    node->nextNodeInLine = prev->nextNodeInLine;
                    prev->nextNodeInLine = node;
                    if (prev == lastNode) {
                        lastNode = (NodeBase *) node;
                    }
                } else { // insert into top
                    (node)->nextNodeInLine = firstNode;
                    firstNode = node;
                }
            }

            ((NodeBase *) node)->codeLine = this;

            return this;
        }

        // append node to the end of the line
        CodeLine *appendNode(void *node) {
            if (firstNode == nullptr) {
                firstNode = (NodeBase *) node;
            }

            if (lastNode != nullptr) {
                if (this->context->appendLineMode == AppendLineMode::Normal) {
                    lastNode->nextNodeInLine = (NodeBase *) node;
                }
            }

            lastNode = (NodeBase *) node;
            if (this->context->appendLineMode == AppendLineMode::Normal) {
                ((NodeBase *) node)->codeLine = this;
            }

            return this;
        }

        // when a node is added to a line, there may be some format nodes like comments/line-breaks, so we need to handle them and attach them to the line as well.
        // New CodeLines will be generated during handling LineBreakNodes, and they will be attached to the last line.
        CodeLine *AddAttachedFormatNodes(void *node) {
            CodeLine *currentCodeLine = this;

            if (this->context->appendLineMode == AppendLineMode::Normal) {
                currentCodeLine = VTableCall::callAppendToLine(((NodeBase *) node)->precedingLineBreakNode, currentCodeLine);
            }

            currentCodeLine = VTableCall::callAppendToLine(((NodeBase *) node)->precedingCommentNode, currentCodeLine);

            return currentCodeLine;
        }
    };


    /**
     * Node Changed Event
     */
    enum EventType {
        CreateDocument,
        FirstLineChanged,
        CreateNode,
        CreateLine,
    };

    /**
     * Defines Managed Coding Operations
     */
    enum class CodingOperations {
        AutoIndentSelection,
        AutoIndentForSpacingRule,
        BreakLine,
        Deletion,
        //AddMapItem
    };

    struct OperationResult {

    };

    struct DocumentUtils {


        static void parseText(DocumentStruct *docStruct, const utf8byte *text, int length);

        static void regenerateCodeLines(DocumentStruct *docStruct);

        static utf8byte *getTextFromTree(DocumentStruct *doc);
        static utf8byte *getTextFromNode(NodeBase *line);
    };


    struct Init {
        static void initNameNode(NameNodeStruct *name, ParseContext *context, void *parentNode);

        static void initSymbolNode(SymbolStruct *self, ParseContext *context, void *parent, utf8byte letter);

        static void initSimpleTextNode(SimpleTextNodeStruct *name, ParseContext *context, void *parentNode, int charLen);
        static void assignText_SimpleTextNode(SimpleTextNodeStruct *name, ParseContext *context, int pos, int charLen);
    };


    struct Alloc {

        static LineBreakNodeStruct *newLineBreakNode(ParseContext *context, NodeBase *parentNode);
        static SimpleTextNodeStruct *newSimpleTextNode(ParseContext *context, NodeBase *parentNode);

        // comment
        static LineCommentNodeStruct *newLineCommentNode(ParseContext *context, NodeBase *parentNode);
        static BlockCommentNodeStruct *newBlockCommentNode(ParseContext *context, NodeBase *parentNode);
        static BlockCommentFragmentStruct *newBlockCommentFragmentNode(ParseContext *context, NodeBase *parentNode);

        static ClassNodeStruct *newClassNode(ParseContext *context, NodeBase *parentNode);

        static DocumentStruct *newDocument(DocumentType docType);

        static void deleteDocument(DocumentStruct *doc);
    };




    /**
     * Function Types and vtable for node structures
     */
    #define TokenizerParams_argNode_ch_start_context \
        NodeBase *argNode, utf8byte ch, st_int start, ParseContext *context

    #define TokenizerParams_pass argNode, ch, start, context
    #define TokenizerParams_pass_3 ch, start, context

    using TokenizerFunction = int (*)(TokenizerParams_argNode_ch_start_context);

    struct Tokenizers {
        static int nameTokenizer(TokenizerParams_argNode_ch_start_context);

        static int classTokenizer(TokenizerParams_argNode_ch_start_context);


        // tokenizer for simple keywords or symbols, like "null", "true", "false", " ", etc... they can be tokenized in one step without backtracking, so we can use this template function to generate them.
        // genereater is a function pointer for generating corresponding node, it will be called when the word is matched, and the generated node will be returned by the tokenizer.
        template<typename TYPE, std::size_t SIZE, typename GENTYPE>
        static inline int tokenizeWord(TokenizerParams_argNode_ch_start_context
                      , GENTYPE* (*genereater)(ParseContext *, NodeBase*)
                      , utf8byte capitalLetter
                      , const TYPE(&word)[SIZE])
        {
            if (capitalLetter == ch) {
                int length = st_size_of(word) - 1;
                if (ParseUtil::matchWordWithTerminatableEnd(context->chars, context->length, start, word)) {
                    auto *boolNode = (SimpleTextNodeStruct*)(genereater(context, argNode));

                    boolNode->text = context->memBuffer.newText(length);
                    boolNode->textLength = length;

                    TEXT_MEMCPY(boolNode->text, context->chars + start, length);
                    boolNode->text[length] = '\0';

                    context->mostLeftNode = Cast::upcast(boolNode);
                    context->generatedPrimaryNode = Cast::upcast(boolNode);
                    return start + length;
                }
            }

            return Search::NOTFOUND;
        }

        // SimpleTextNodeStruct
        template<typename TYPE, std::size_t SIZE>
        static inline int WordTokenizer(TokenizerParams_argNode_ch_start_context
                , utf8byte capitalLetter
                , const TYPE(&word)[SIZE])
        {
            return tokenizeWord(TokenizerParams_pass, Alloc::newSimpleTextNode, capitalLetter, word);
        }
    };


    /**
     * Implements common scanning and parsing method
     */
    struct Scanner {
        static int scanRoot(void *parentNode, TokenizerFunction tokenizer, ParseContext *context);

        static int scanOnce(void *parentNode, TokenizerFunction tokenizer, ParseContext *context, int start);

        static int scanLoop(void *parentNode, TokenizerFunction tokenizer, ParseContext *context, int start);
    };
}