#pragma once

#include <stdlib.h>
#include <array>
#include <utility> // std::declval

#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <chrono>
#include <unordered_map>

#include <cstdint> // uint64_t, int_fast32_t
#include <ctime>

#include <string.h> // memcpy


#include "ParseUtil.hpp"
#include "common.hpp"
#include "errors.hpp"

namespace cshort {

    struct ParseContext;
    struct CodeLine;
    struct TypeManager;
    struct _scriptEngineContext;
    struct LocalVariableChain;
    enum class GRPRegisterEnum;
    
    #define NODE_TYPE_ID 0x123
    #define TOKEN_TYPE_ID 0x456

    #define COMMON_HEADER \
        int type_id; \
        _NodeBase *parentNode; \
        CodeLine *codeLine; \
        ParseContext *context; \

    #define NODE_HEADER \
        COMMON_HEADER \
        const struct node_vtable *vtable; /* virtual table */ \
        _NodeBase *nextNode; \
        GRPRegisterEnum calcRegEnum; \
        st_byte *calcReg;                 \
        int typeIndex;                \

    #define TOKEN_HEADER \
        COMMON_HEADER \
        const struct token_vtable *vtable; /* virtual table */ \
        _TokenBase *nextToken; \
        _TokenBase *nextTokenInLine; \
        int foundPos; \
        /* precedingSpaceCount holds number of chars before this node, used for error reporting and code generation. */ \
        /* this reduces memory usage and keeps AST simple by avoid creating additional nodes for all spaces. */ \
        int precedingSpaceCount; \
        void *precedingCommentToken; \
        /* the first linebreak node before the code node generated by tokenizer  */ \
        struct _LineBreakTokenStruct *precedingLineBreakToken; \


    #define SIMPLE_TEXT_CONTENT \
        utf8byte *text; \
        int_fast32_t textLength;

    enum class TypeIndexConst {
        NotAssigned = -1,
        Empty = 0,
    };

    // value base is used for storing values of variables, literals, and temporary results during expression evaluation.
    using TypedValue = struct _typedValue {
        int typeIndex;
        void* ptr;
        unsigned int size; // in byte
    };

    enum class BuildinTypeId {
        Int32 = 1,
        Int64 = 2,
        HeapString = 23,
        Null = 24,
        Bool = 3,
    };


    using type_index = int;
    const int ErrorTypeIndex = -1;
    struct BuiltInTypeIndex {
        static int int32;
        static int int64;
        static int boolIdx;
        static int null;
        static int heapString;
    };

    #define INIT_NODE(node, context, parent, argvtable) \
        (node)->vtable = (argvtable); \
        (node)->type_id = NODE_TYPE_ID; \
        (node)->context = (context); \
        (node)->parentNode = (NodeBase*)(parent); \
        (node)->codeLine = nullptr; \
        (node)->nextNode = nullptr; \
        (node)->typeIndex = (int)TypeIndexConst::NotAssigned; \
        (node)->calcRegEnum = (GRPRegisterEnum)0; \
        (node)->calcReg = nullptr; \
        (0)

    #define INIT_TOKEN(token, context, parent, argvtable) \
        (token)->vtable = (argvtable); \
        (token)->type_id = TOKEN_TYPE_ID; \
        (token)->precedingSpaceCount = 0; \
        (token)->context = (context); \
        (token)->parentNode = (NodeBase*)(parent); \
        (token)->codeLine = nullptr; \
        (token)->foundPos = -1; \
        (token)->nextToken = nullptr; \
        (token)->nextTokenInLine = nullptr; \
        (token)->precedingLineBreakToken = nullptr; \
        (token)->precedingCommentToken = nullptr; \
        (0)

    #define TEXT_MEMCPY(dst, src, len) \
        memcpy((dst), (src), (len))

    using NodeBase = struct _NodeBase {
        NODE_HEADER;
    };

    using TokenBase = struct _TokenBase {
        TOKEN_HEADER;
    };

    using SimpleTextTokenStruct = struct _SimpleTextTokenStruct {
        TOKEN_HEADER;

        SIMPLE_TEXT_CONTENT;
    };

    using KeywordTokenStruct = SimpleTextTokenStruct;


    using LineCommentTokenStruct = SimpleTextTokenStruct;
    using BlockCommentFragmentStruct = SimpleTextTokenStruct;
    using ConstLiteralTokenStruct = SimpleTextTokenStruct; // null, false, true

    // LineBreakTokenStruct is used for storing line break info for error reporting and code generation.
    using LineBreakTokenStruct = struct _LineBreakTokenStruct {
        TOKEN_HEADER;

        utf8byte text[3]; // "\r\n", "\n", "\r" or "\0"
        _LineBreakTokenStruct *nextLineBreak;
    };

    using BlockCommentTokenStruct = struct _BlockCommentTokenStruct {
        TOKEN_HEADER;

        BlockCommentFragmentStruct *firstCommentFragment;
        char* tagText; // for named block comment /*<[hoge] ... [hoge]>*/
        int tagTextLength;
    };


    using EndOfFileNodeStruct = struct _EndOfFileNodeStruct {
        NODE_HEADER;

        SimpleTextTokenStruct eofToken;
    };


    using IdentifierTokenStruct = struct _IdentifierTokenStruct {
        TOKEN_HEADER;

        int stackOffset;
        char *name;
        int_fast32_t nameLength;
    };

    using SymbolTokenStruct = struct _SymbolTokenStruct {
        TOKEN_HEADER;

        bool isEnabled;
        utf8byte symbol[2];
        bool isEndFlag;
    };

    
    using NumberNodeStruct = struct _NumberNodeStruct {
        NODE_HEADER;

        SimpleTextTokenStruct originalNumberTextToken;

        int64_t num;
        int unit;
    };

    // namespace::ClassName.Property
    // namespace::Method() // () excluded, Expression tokenizer will deal with it.
    // localVariable
    using IdentifiersAccessNodeStruct = struct _IdentifiersAccessNodeStruct {
        NODE_HEADER;
        int stackOffset;

        IdentifierTokenStruct identifierToken;
    };

    using ParenthesesNodeStruct = struct _ParenthesesNodeStruct {
        NODE_HEADER;

        SymbolTokenStruct openNode;
        SymbolTokenStruct closeNode;

        NodeBase *valueNode;
    };

    using ClassNodeStruct = struct _ClassNodeStruct {
        NODE_HEADER;

        KeywordTokenStruct classKeywordToken;
        IdentifierTokenStruct identifierToken;

        struct Impl;
        struct Impl *sub;

        bool startFound;

        SymbolTokenStruct bodyStartSymbolToken;
        SymbolTokenStruct endBodySymbolToken;

        NodeBase *firstChildNode;
        NodeBase *lastChildNode;
        int childCount;
    };

    // ?string *
    using TypeNodeStruct = struct _TypeNodeStruct {
        NODE_HEADER;

        SIMPLE_TEXT_CONTENT;

        bool hasImmutableMark; // # immutable
        bool hasNullableMark; // ? nullable
        bool isLet; // or has type
        
        SymbolTokenStruct pointerAsterisk; // *

        IdentifierTokenStruct nameNode; // type name like int, string, etc..
        SimpleTextTokenStruct typeTextToken; // including ? or #
    };

    
    using StringLiteralTokenStruct = struct _StringLiteralTokenStruct {
        TOKEN_HEADER;
        char *text; // unparsed text including ""
        int_fast32_t textLength;

        char *str;
        int strLength;

        int literalType; // 0: "text", 1: `text`
    };


    // true, false, null
    using LiteralValueNodeStruct = struct _LiteralValueStruct {
        NODE_HEADER;

        bool isTrue;
        bool isFalse;
        bool isNull;
        bool isStringLiteral;

        ConstLiteralTokenStruct *textToken;
        // if this literal is string, store the string literal node here for code generation.
        StringLiteralTokenStruct *stringLiteralToken;
    };
    

    // int a = 5
    // immutable: #int a = 5
    // nullable: ?let *ptr = "jfwio"
    using AssignmentNodeStruct = struct _AssignmentNodeStruct {
        NODE_HEADER;

        TypeNodeStruct typeOrLet; // #let, int, ?string, etc..
        bool hasTypeOrLet; // only assignment: a = 3
        bool hasTypeDecl() {
            return hasTypeOrLet && !typeOrLet.isLet;
        }

        //SymbolTokenStruct pointerAsterisk; // *

        int stackOffset; // stack offset for this variable from the base stack pointer
        IdentifierTokenStruct variableNameToken; // variable name
        SymbolTokenStruct equalSymbol; // =
        NodeBase *expressionNode; // 32

        bool isExpressionFirstSyntax; // for handling multiple line assign statement
    };

    using KeywordAndExpressionStruct = struct _KeywordAndExpressionStruct {
        NODE_HEADER;

        SimpleTextTokenStruct returnText;
        NodeBase *expressionNode;
    };

    using ReturnStatementNodeStruct = KeywordAndExpressionStruct;



    // Only assignment, call, increment, decrement, and new object expressions can be used as a statement
    using FuncBodyNodeStruct = struct _BodyNodeStruct {
        NODE_HEADER;

        bool startFound;
        bool firstStatementFound;

        SymbolTokenStruct bodyStartNode;
        SymbolTokenStruct endBodyNode;
        
        LocalVariableChain *localVariableChain;

        NodeBase *firstChildNode;
        NodeBase *lastChildNode;
        int childCount;
    };



    // (?int point = null)
    using FuncParameterItemStruct = struct _FuncParameterItemStruct {
        NODE_HEADER;
        AssignmentNodeStruct *assignmentNodeStruct;
        SymbolTokenStruct  followingComma;
        bool hasComma;
    };

    using FuncDefNodeStruct = struct _FuncNodeStruct {
        NODE_HEADER;

        SimpleTextTokenStruct fnKeywordToken; // "fn"
        IdentifierTokenStruct funcNameToken;
        int stackSize;

        SymbolTokenStruct parameterStartNode; // (
        SymbolTokenStruct parameterEndNode; // )

        FuncBodyNodeStruct bodyNode;
        VoidHashMap *localVariableMap;

        int parameterParsePhase;
        FuncParameterItemStruct *firstChildParameterNode;
        FuncParameterItemStruct *lastChildParameterNode;
        int parameterChildCount;
    };


    using FuncCallArgItemStruct = struct _FuncArgumentItemStruct {
        NODE_HEADER;

        NodeBase *exprNode; // expression Node
        SymbolTokenStruct follwingComma;
        bool hasComma;
    };


    // func(23, "str")
    using FuncCallNodeStruct = struct _FuncCallNodeStruct {
        NODE_HEADER;

        NodeBase *callerExprNode; // this can be a variable or a property access like obj.method, or even a func call like getFunc()()
        int parsePhase;
        SymbolTokenStruct openParenthesisToken;
        SymbolTokenStruct closeParenthesisToken;

        FuncCallArgItemStruct *firstArgumentItem;
        FuncCallArgItemStruct *lastArgumentItem;
    };


    enum BinaryOperator {
        Add, // +
        Subtract, // -
        Multiply, // *
        Divide, // /
        Modulo, // %
        And, // &&
        Or, // ||
        BitwiseAnd, // &
        BitwiseOr, // |
    };

    enum BinaryOperationGroup { // group by priority of operators
        Add_Subtract, // +, - 
        Multiply_Divide_Modulo, // *,/,%
        And_Or, // &&, ||
        BitwiseAnd_BitwiseOr, // &, |
        None, // no found
    };

    const BinaryOperationGroup LowestBinaryOperationGroup = BinaryOperationGroup::Add_Subtract; // the group with lowest priority

    // temporary node used for parsing binary expression, converted to BinaryOperationNodeStruct after parsing is finished.
    using TempOpItem = struct _OpItemNodeStruct {
        NODE_HEADER;

        NodeBase *rightExprNode;
        SymbolTokenStruct opToken; // left operator token

        BinaryOperationGroup opGroup;
        BinaryOperator binaryOp; // specific operator like Add, Subtract, etc.. used for code generation and type checking.

        struct _OpItemNodeStruct *nextOpNode;
    };

    
    using BinaryOperationNodeStruct = struct _BinaryOperationNodeStruct {
        NODE_HEADER;
        
        SymbolTokenStruct opToken; // op can be +, -, *, /, %, etc..
        BinaryOperationGroup opGroup;
        BinaryOperator binaryOp; 
        // if true, the left and right expression nodes do not need to save their registers, used for optimization
        bool noNeedToSaveRegisters;

        NodeBase *leftExprNode;
        NodeBase *rightExprNode;
         
        bool useLeftAsBase;
    };

    enum DocumentType {
        CodeDocument,
        JsonDocument,// for LSP server
    };

    using DocumentStruct = struct _documentStruct {
        NODE_HEADER;

        DocumentType documentType;
        char *fileName;
        EndOfFileNodeStruct endOfFile;

        int nodeCount{0};

        CodeLine *firstCodeLine;
        int lineCount;

        NodeBase *firstRootNode;
        NodeBase *lastRootNode;

        FuncDefNodeStruct* mainFunc;
    };


    enum class AppendLineMode {
        Normal,
        DetectErrorSpanTokens // add tokens only on the line that has syntax error, used for LSP server to reduce unnecessary addition.
    };


    struct ValidationContext {
        DocumentStruct *document;
        MemBuffer memBuffer;
        void init() {
            memBuffer.init();
        }
    };

    struct ParseContext {
        st_uint start;
        int length;
        bool scanEnd; // used for tokenizer to indicate the end of scan.
        AppendLineMode appendLineMode; // 0:
        int lastTokenizedPos; // used for error reporting 

        bool isAfterLineBreak; // for loopMode=true tokenizer
        TokenBase *mostLeftToken; // store the most left token generated by tokenizer,
                                // used for assigning line break and comment tokens in scanWithTokenizer
        NodeBase *generatedPrimaryNode; // store the primary node generated by tokenizer, used for dealing with it in caller.
        const utf8byte *chars;

        ClassNodeStruct *unusedClassNode;
        AssignmentNodeStruct *unusedAssignment;
        CodeLine *baseCodeLine; // used for storing the code line with base indent, used for calculating indent for other lines.
        int baseindentDepth;
        bool baseIncrementMode;

        bool skipBinaryExpressionTokenizer;
        
        // used for tokenizer to indicate that it is inside parentheses expression, so that it can parse binary expression inside parentheses even if skipBinaryExpressionTokenizer is true.
        bool insideParenthesisExpression;

        LineBreakTokenStruct *remainedLineBreakToken;
        void *remainedCommentToken;
        int remainedSpaceCount{0};

        MemBuffer memBuffer;
        MemBuffer memBufferForCodeLines;
        MemBuffer memBufferForError;
        MemBuffer memBufferForValidation;

        SyntaxErrorInfo syntaxErrorInfo;
        SemanticErrorInfo semanticErrorInfo;

        struct _scriptEngineContext *scriptEngineContext;
        TypeManager *typeManager;

        void init();
        void dispose();

        template<typename T>
        T *newMem() {
            return (T *) memBuffer.newMem<T>(1);
        }

        template<typename T>
        void tryDelete(T *m) {
            memBuffer.tryDelete(m);
        }

        template<typename T>
        T *newMemArray(st_size len) {
            return (T *) memBuffer.newMem<T>(len);
        }
        utf8byte *newText(st_size len) {
            return memBuffer.newText(len);
        }


        LineBreakTokenStruct *newLineBreakToken() {
            return memBuffer.newMem<LineBreakTokenStruct>(1);
        }

        CodeLine *newCodeLine() {
            return memBufferForCodeLines.newMem<CodeLine>(1);
        }

        template<typename T>
        T *newMemForNode() {
            return memBuffer.newMem<T>(1);
        }

        int IncrementIndentDepth(ParseContext *context);
        int IncrementIndentDepthForParenthesis(ParseContext *context);
        void DecrementIndentDepth(ParseContext *context);
        
        int baseIndent;
        bool has_depth_error{false};
        int currentIndentDepth { -1 };
        bool isAfterOpenParenthesis { false }; // used for indent depth calculation, when true, indent depth will be increased by 1 for the line after current line until the closing parenthesis(expression level) is found.
        bool incrementDepthOnNextLine{false}; // when true, the next line break will increase indent depth by 1.
        int arithmeticBaseDepth{ -1 };

        void setError(ErrorIndex errorCode, st_int startPos);

        int getNextLineIndentDepth() const;

        void setError2(ErrorIndex errorCode, st_int startPos, st_int startPos2);
        void setIndentError(ErrorIndex errorCode, st_int line1, st_int charPos1);
        void setError3(ErrorIndex errorCode, st_int line1, st_int charPos1, st_int line2, st_int charPos2);
        void addErrorWithNode(ErrorIndex errorCode, void* nodeArg) ;
    };




    struct Cast {
        template<typename T>
        static inline T downcast(void *node) {
            return (T) node;
        }

        template<typename T>
        static inline NodeBase *upcast(T *node) {
            auto *n =  (NodeBase *) node;
            assert(n->type_id == NODE_TYPE_ID);
            return n;
        }

        template<typename T>
        static inline TokenBase *upcastToken(T *token) {
            auto *t = (TokenBase *) token;
            assert(t->type_id == TOKEN_TYPE_ID);
            return t;
        }
    };

    enum class NodeTypeId {
        Document = 0,
        EndOfDoc = 1,
        Class = 4,
        Func = 17,
        Body = 19,
        Type = 18,
        Assignment = 20,
        ReturnStatement = 24,
        Parentheses = 26,
        FuncCall = 27,
        FuncArgument = 28,
        FuncParameter = 29,
        BinaryOperation = 30,
        OpItem = 31,
        IdentifiersAccess = 25,
        FixedLiteral = 32,
        Number = 33,
    };

    enum class TokenTypeId {

        StringLiteral = 2,
        Symbol = 3,
        Identifier = 5,
        SimpleText = 6,

        Number = 9,
        LineBreak = 10,
        Bool = 11,
        ConstLiteral = 12,
        
        NULLId = 16,
        
        LineComment = 21,
        BlockComment = 22,
        BlockCommentFragment = 23,
    };



    #define ApplyFunc_params3 \
        ParseContext *context, \
        void *targetVTable, \
        int (*func)(NodeBase *, cshort::ParseContext *context, void *targetVTable,void *func, bool parentIsFirst, void *arg, void *arg2), \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2

    #define TokenApplyFunc_params3 \
        ParseContext *context, \
        void *targetVTable, \
        int (*func)(TokenBase *, cshort::ParseContext *context, void *targetVTable,void *func, bool parentIsFirst, void *arg, void *arg2), \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2


    #define ApplyFunc_params2 \
        ParseContext *context, \
        void *targetVTable, \
        void *func, \
        bool parentIsFirst,           \
        void *topLevelNodeInBody,           \
        void *arg2


    #define ApplyFunc_pass \
                context, \
                targetVTable, (void *)func, parentIsFirst, topLevelNodeInBody, arg2

    #define ApplyFunc_pass2 \
                context, \
                targetVTable, func, parentIsFirst, topLevelNodeInBody, arg2


    #define NODE_VTABLE_DEF(T) \
        int (*selfTextLength)(T *self); \
        /* no need to add null terminator, caller will add it using selfTextLength() */ \
        void (*copySelfText)(T *self, utf8byte *buf); \
        CodeLine *(*appendToLine)(T *self, CodeLine *line); \
        int (*applyFuncToDescendants)(T *Node, ApplyFunc_params3); \
        const char *typeChars; \
        int typeCharsLength; \
        int (*typeSelector)(NodeBase *self);     \
        NodeTypeId nodeTypeId; \

    #define TOKEN_VTABLE_DEF(T) \
        int (*selfTextLength)(T *self); \
        /* no need to add null terminator, caller will add it using selfTextLength() */ \
        void (*copySelfText)(T *self, utf8byte *buf); \
        CodeLine *(*appendToLine)(T *self, CodeLine *line); \
        int (*applyFuncToDescendants)(T *Node, TokenApplyFunc_params3); \
        const char *typeChars; \
        int typeCharsLength; \
        int (*typeSelector)(TokenBase *self);     \
        TokenTypeId nodeTypeId; \


    /**
     * Node vtable
     */
    using NodeVTable = struct node_vtable {
        NODE_VTABLE_DEF(NodeBase)
    };

    /**
     * token vtable
     */
    using TokenVTable = struct token_vtable {
        TOKEN_VTABLE_DEF(TokenBase)
    };



    // this is for static type checking
    template<typename T>
    struct nodeVirtualTable {
        NODE_VTABLE_DEF(T)
    };

    template<typename T>
    struct tokenVirtualTable {
        TOKEN_VTABLE_DEF(T)
    };


    using selfTextLengthFunction = decltype(std::declval<NodeVTable>().selfTextLength);
    using selfTextFunction = decltype(std::declval<NodeVTable>().copySelfText);
    using appendToLineFunction = decltype(std::declval<NodeVTable>().appendToLine);
    using applyFuncToDescendantsFunction = decltype(std::declval<NodeVTable>().applyFuncToDescendants);

    template<typename T, std::size_t SIZE>
    static int vtable_type_check(
            decltype(std::declval<nodeVirtualTable<T>>().selfTextLength) f1,
            decltype(std::declval<nodeVirtualTable<T>>().copySelfText) f2,
            decltype(std::declval<nodeVirtualTable<T>>().appendToLine) f3,
            decltype(std::declval<nodeVirtualTable<T>>().applyFuncToDescendants) f4,
            const char(&f5)[SIZE],
            NodeTypeId f6
    ) noexcept {
        return 0;
    }



    #define CREATE_VTABLE(T, f1, f2, f3, f4, f5, f6) \
        node_vtable { \
            reinterpret_cast<selfTextLengthFunction> (f1) \
            , reinterpret_cast<selfTextFunction> (f2) \
            , reinterpret_cast<appendToLineFunction> (f3) \
            , reinterpret_cast<applyFuncToDescendantsFunction> (f4) \
            , (const char *)(f5) \
            , (sizeof(f5)-1) \
            , nullptr \
            , f6 \
        } \
        ;static const int check_result_##T = vtable_type_check<T>(f1,f2,f3,f4,f5,f6)

    
    using token_selfTextLengthFunction = decltype(std::declval<TokenVTable>().selfTextLength);
    using token_selfTextFunction = decltype(std::declval<TokenVTable>().copySelfText);
    using token_appendToLineFunction = decltype(std::declval<TokenVTable>().appendToLine);
    using token_applyFuncToDescendantsFunction = decltype(std::declval<TokenVTable>().applyFuncToDescendants);

    template<typename T, std::size_t SIZE>
    static int token_vtable_type_check(
        decltype(std::declval<tokenVirtualTable<T>>().selfTextLength) f1,
        decltype(std::declval<tokenVirtualTable<T>>().copySelfText) f2,
        decltype(std::declval<tokenVirtualTable<T>>().appendToLine) f3,
        decltype(std::declval<tokenVirtualTable<T>>().applyFuncToDescendants) f4,
        const char(&f5)[SIZE],
        TokenTypeId f6
    ) noexcept {
        return 0;
    }

    #define CREATE_TOKEN_VTABLE(T, f1, f2, f3, f4, f5, f6) \
        token_vtable { \
            reinterpret_cast<token_selfTextLengthFunction> (f1) \
            , reinterpret_cast<token_selfTextFunction> (f2) \
            , reinterpret_cast<token_appendToLineFunction> (f3) \
            , reinterpret_cast<token_applyFuncToDescendantsFunction> (f4) \
            , (const char *)(f5) \
            , (sizeof(f5)-1) \
            , nullptr \
            , f6 \
        } \
        ;static const int check_result_##T = token_vtable_type_check<T>(f1,f2,f3,f4,f5,f6)


    struct VTables {
        static const node_vtable
                *DocumentVTable,
                *ClassVTable,
                *FuncDefVTable,
                *FuncBodyVTable,
                *EndOfFileVTable,
                *FuncParameterVTable,
                *AssignmentVTable,
                *ReturnStatementVTable,
                *TypeVTable,
                *FixedLiteralVTable,
                *NumberVTable,
                *ParenthesesVTable,
                *IdentifiersAccessVTable,
                *FuncCallArgVTable,
                *FuncCallVTable,
                *BinaryOperationVTable
                ;

        static const token_vtable
                *ConstLiteralVTable,     
                *LineBreakVTable,
                *LineCommentVTable,
                *BlockCommentFragmentVTable,
                *SimpleTextVTable,
                *BlockCommentVTable,
                *IdentifierTokenVTable,
                *StringLiteralTokenVTable,
                *SymbolTokenVTable,
                *LineBreakTokenVTable
                ;
    };




    struct VTableCall {

        static int selfTextLength(NodeBase *node) {
            assert(node);
            assert(node->vtable);
            assert(node->vtable->selfTextLength);

            return node->vtable->selfTextLength(node);
        }


        static inline void copySelfText(void *node, char *buf) {
            if (node == nullptr) {
                return;
            } else {
                auto *nodeBase = Cast::upcast(node);
                nodeBase->vtable->copySelfText(nodeBase, buf);
            }
        }

        static int typeTextLength(NodeBase *node) {
            assert(node);
            assert(node->vtable);
            return node->vtable->typeCharsLength;
        }


        static inline const utf8byte *typeText(void *node) {
            if (node == nullptr) {
                return "";
            } else {
                auto *nodeBase = Cast::upcast(node);
                return nodeBase->vtable->typeChars;
            }
        }


        // forward declaration of functions in parser_core.cpp to avoid circular dependency 
        static inline CodeLine *callAppendNodeToLine(void *node, CodeLine *currentCodeLine) {
            if (node == nullptr) { // BreakLineToken can be null
                return currentCodeLine;
            }
            auto *nodeBase = Cast::upcast(node);
            assert(nodeBase->type_id == NODE_TYPE_ID);

            return nodeBase->vtable->appendToLine(nodeBase, currentCodeLine);
        }
    };

    struct TokenVTableCall {

        static int selfTextLength(TokenBase *token) {
            assert(token);
            assert(token->vtable);
            assert(token->vtable->selfTextLength);

            return token->vtable->selfTextLength(token);
        }

        static inline void copySelfText(void *token, char *buf) {
            if (token == nullptr) {
                return;
            } else {
                auto *tokenBase = Cast::upcastToken(token);
                tokenBase->vtable->copySelfText(tokenBase, buf);
            }
        }

        static int typeTextLength(TokenBase *token) {
            assert(token);
            assert(token->vtable);
            return token->vtable->typeCharsLength;
        }

        static inline const utf8byte *typeText(void *token) {
            if (token == nullptr) {
                return "";
            } else {
                auto *tokenBase = Cast::upcastToken(token);
                return tokenBase->vtable->typeChars;
            }
        }

        // forward declaration of functions in parser_core.cpp to avoid circular dependency 
        static inline CodeLine *callAppendTokenToLine(void *token, CodeLine *currentCodeLine) {
            if (token == nullptr) { // BreakLineToken can be null
                return currentCodeLine;
            }

            auto *tokenBase = Cast::upcastToken(token);
            assert(tokenBase->type_id == TOKEN_TYPE_ID);
            if (tokenBase->foundPos < 0) {
                printf("no foundPos > -1: %s\n", typeText(tokenBase));
            }
            assert(tokenBase->foundPos >= 0);

            // if the token has precedingLineBreakToken, append the precedingLineBreakToken before appending the token itself,
            // so that the line break will be before the token in the code line,
            // which is more intuitive and easier to handle when generating code later
            return tokenBase->vtable->appendToLine(tokenBase, currentCodeLine);
        }
    };

    struct CodeLine {
        CodeLine *nextLine;
        int lineNumber;
        //CodeLine *prev;
        TokenBase *firstToken;
        TokenBase *lastToken;
        // int indent;
        ParseContext *context;

        int depth;

        void init(ParseContext *argContext) {
            this->context = argContext;
            this->lineNumber = 0;

            this->firstToken = nullptr;
            this->lastToken = nullptr;
            this->nextLine = nullptr;
            ///this->prev = nullptr;
            this->depth = 0;
        }

        static inline bool HasOnlyEndParentheses(CodeLine *line) {
            auto token = line->firstToken;
            while (token != nullptr) {
                auto currentToken = token;
                token = token->nextTokenInLine; // assign next token before checking current token

                if (currentToken->vtable == VTables::BlockCommentFragmentVTable
                     || currentToken->vtable == VTables::BlockCommentVTable) {
                    continue;
                }

                if (currentToken->vtable != VTables::SymbolTokenVTable) {
                    return false;
                }

                auto *symbolToken = Cast::downcast<SymbolTokenStruct *>(currentToken);
                if (!symbolToken->isEndFlag) {
                    return false;
                }
            }
            return true;
        }
        
        // insert token into this line, if prev is null, insert it into top of the line
        CodeLine *insertToken(TokenBase *token, TokenBase *prev) {
            if (firstToken == nullptr) {
                assert(prev == nullptr);
                firstToken = token;
                lastToken = token;
            } else {
                if (prev != nullptr) { // insert it after prev
                    token->nextTokenInLine = prev->nextTokenInLine;
                    prev->nextTokenInLine = token;
                    if (prev == lastToken) {
                        lastToken = (TokenBase *) token;
                    }
                } else { // insert into top
                    (token)->nextTokenInLine = firstToken;
                    firstToken = token;
                }
            }

            ((TokenBase *) token)->codeLine = this;

            return this;
        }

        // append token to the end of the line
        CodeLine *appendToken(void *token) {
            if (firstToken == nullptr) {
                firstToken = (TokenBase *) token;
            }

            if (lastToken != nullptr) {
                if (this->context->appendLineMode == AppendLineMode::Normal) {
                    lastToken->nextTokenInLine = (TokenBase *) token;
                }
            }

            lastToken = (TokenBase *) token;
            assert(lastToken->type_id == TOKEN_TYPE_ID);
            assert(lastToken->parentNode != nullptr);
            if (this->context->appendLineMode == AppendLineMode::Normal) {
                ((TokenBase *) token)->codeLine = this;
            }

            return this;
        }

        // when a token is added to a line, there may be some format tokens like comments/line-breaks, so we need to handle them and attach them to the line as well.
        // New CodeLines will be generated during handling LineBreakTokens, and they will be attached to the last line.
        CodeLine *AddAttachedFormatTokens(void *token) {
            CodeLine *currentCodeLine = this;

            if (this->context->appendLineMode == AppendLineMode::Normal) {
                currentCodeLine = TokenVTableCall::callAppendTokenToLine(((TokenBase *) token)->precedingLineBreakToken, currentCodeLine);
            }

            currentCodeLine = TokenVTableCall::callAppendTokenToLine(((TokenBase *) token)->precedingCommentToken, currentCodeLine);

            return currentCodeLine;
        }
    };

    

    // this struct is used for applying indent rules when appending code lines,
    // it will save the indent state when created, and restore the indent state when finished.
    struct IndentRuleApplier {
        ParseContext *context;
        CodeLine *firstLine;
        int firstDepth;
        bool firstIncrementMode;
        int baseDepth;

        bool isExpressionMode;
        int savedPos;
        bool savedIncrementMode;

        static IndentRuleApplier Create(ParseContext *context, CodeLine *currentCodeLine) {
            IndentRuleApplier indentRuleApplier = IndentRuleApplier();
            indentRuleApplier.Init(context, currentCodeLine, false);
            return indentRuleApplier;
        }

        static IndentRuleApplier CreateForExpression(ParseContext *context, CodeLine *currentCodeLine) {
            IndentRuleApplier indentRuleApplier = IndentRuleApplier();
            indentRuleApplier.Init(context, currentCodeLine, false, true);
            return indentRuleApplier;
        }

        static IndentRuleApplier CreateWithBase(ParseContext *context, CodeLine *currentCodeLine) {
            IndentRuleApplier indentRuleApplier = IndentRuleApplier();
            indentRuleApplier.Init(context, currentCodeLine, true);
            return indentRuleApplier;
        }

        void saveCurrentPos() {
            this->savedPos = this->context->currentIndentDepth;
            this->savedIncrementMode = this->context->incrementDepthOnNextLine;
        }

        void restorePos() {
            this->context->currentIndentDepth = this->savedPos;
            this->context->incrementDepthOnNextLine = this->savedIncrementMode;
        }

        void Init(ParseContext *context, CodeLine *currentCodeLine, bool useBase, bool expressionMode = false) {
            assert(context != nullptr);

            this->context = context;
            this->isExpressionMode = expressionMode;
            
            if (useBase) {
                this->baseDepth = context->baseindentDepth + (context->baseIncrementMode ? 1 : 0);
                this->firstDepth = context->baseindentDepth;
                this->firstLine = context->baseCodeLine;
                this->firstIncrementMode = context->baseIncrementMode;
            }
            else {
                this->baseDepth = expressionMode ? context->currentIndentDepth : context->getNextLineIndentDepth();
                this->firstLine = currentCodeLine;
                this->firstDepth = context->currentIndentDepth;
                this->firstIncrementMode = context->incrementDepthOnNextLine;
            }
        }

        int GetBaseDepth() const {
            return baseDepth;
        }
        
        void StartBracket(CodeLine *currentCodeLine) {
            if (currentCodeLine != firstLine/* && !this->isExpressionMode*/) {
                currentCodeLine->depth = baseDepth;
                context->currentIndentDepth = baseDepth;
            }
            context->incrementDepthOnNextLine = true;
        }

        void FinishAfterEndBracket(CodeLine *codeLine) {
            if (CodeLine::HasOnlyEndParentheses(codeLine)) {
                codeLine->depth = baseDepth;
            }
            
            if (codeLine == firstLine) {
                context->currentIndentDepth = firstDepth;
                context->incrementDepthOnNextLine = firstIncrementMode;
            }
            else {
                context->currentIndentDepth = baseDepth;
                context->incrementDepthOnNextLine = false;
            }
        }
    };

    /**
     * Node Changed Event
     */
    enum EventType {
        CreateDocument,
        FirstLineChanged,
        CreateNode,
        CreateLine,
    };

    /**
     * Defines Managed Coding Operations
     */
    enum class CodingOperations {
        AutoIndentSelection,
        AutoIndentForSpacingRule,
        BreakLine,
        Deletion,
        //AddMapItem
    };

    struct OperationResult {

    };

    struct DocumentUtils {
        static void parseText(DocumentStruct *docStruct, const utf8byte *text, int length);

        static void regenerateCodeLines(DocumentStruct *docStruct);

        static utf8byte *getTextFromTree(DocumentStruct *doc);
    };



    struct Init {
        // Nodes
        static void initFuncBodyNode(FuncBodyNodeStruct *node, ParseContext *context, void *parentNode);
        static void initTypeNode(TypeNodeStruct *self, ParseContext *context, void *parent);

        static void initAssignment(ParseContext *context, NodeBase *parentNode,
                                       AssignmentNodeStruct *assignment
        );

        static void initReturnStatement(ParseContext *context, NodeBase *parentNode,
                                        ReturnStatementNodeStruct *returnStatement
        );
        // Tokens
        static void initIdentifierToken(IdentifierTokenStruct *name, ParseContext *context, void *parentNode);

        static void initSymbolToken(SymbolTokenStruct *self, ParseContext *context, void *parent, utf8byte letter);

        static void initSimpleTextToken(SimpleTextTokenStruct *textToken, ParseContext *context, void *parentNode, int charLen);
        static void assignText_SimpleTextToken(SimpleTextTokenStruct *textToken, ParseContext *context, const utf8byte *text, int charLen);
        static void initStringLiteralNode(StringLiteralTokenStruct *name, ParseContext *context,
                                          NodeBase *parentNode);

    };


    struct Alloc {

        // Tokens
        static LineBreakTokenStruct *newLineBreakToken(ParseContext *context, void *parentNode);
        static SimpleTextTokenStruct *newSimpleTextToken(ParseContext *context, NodeBase *parentNode);

        static LineCommentTokenStruct *newLineCommentToken(ParseContext *context, void *parentNode);
        static BlockCommentTokenStruct *newBlockCommentToken(ParseContext *context, void *parentNode);
        static BlockCommentFragmentStruct *newBlockCommentFragmentToken(ParseContext *context, BlockCommentTokenStruct *parentNode);
        static ConstLiteralTokenStruct *newConstLiteralToken(ParseContext *context, NodeBase *parentNode);
        static StringLiteralTokenStruct *newStringLiteralToken(ParseContext *context, NodeBase *parentNode);

        // Nodes
        static ClassNodeStruct *newClassNode(ParseContext *context, NodeBase *parentNode);
        static LiteralValueNodeStruct *newLiteralValueNode(ParseContext *context, NodeBase *parentNode);
        static NumberNodeStruct *newNumberNode(ParseContext *context, NodeBase *parentNode);

        static DocumentStruct *newDocument(DocumentType docType);
        static void deleteDocument(DocumentStruct *doc);

        static TypeNodeStruct *newTypeNode(ParseContext *context, NodeBase *parentNode);

        static AssignmentNodeStruct *newAssignment(ParseContext *context, NodeBase *parentNode);
        static ReturnStatementNodeStruct *newReturnStatement(ParseContext *context, NodeBase *parentNode);

        static FuncDefNodeStruct *newFuncNode(ParseContext *context, NodeBase *parentNode);

        static FuncParameterItemStruct *newFuncParameterItem(ParseContext *context, NodeBase *parentNode);

        static ParenthesesNodeStruct *newParenthesesNode(ParseContext *context, NodeBase *parentNode);
        static IdentifiersAccessNodeStruct *newIdentifiersAccessNode(ParseContext *context, NodeBase *parentNode);

        static FuncCallArgItemStruct *newFuncCallArgItem(ParseContext *context, NodeBase *parentNode);
        static FuncCallNodeStruct *newFuncCallNode(ParseContext *context, NodeBase *parentNode);

        static BinaryOperationNodeStruct *newBinaryOperationNode(ParseContext *context, NodeBase *parentNode);
    };




    /**
     * Function Types and vtable for node structures
     */
    #define TokenizerParams_argNode_ch_start_context \
        void *argNode, utf8byte ch, st_int start, ParseContext *context


    #define TokenizerParams_pass argNode, ch, start, context
    #define TokenizerParams_pass_3 ch, start, context

    using TokenizerFunction = int (*)(TokenizerParams_argNode_ch_start_context);

    struct NodeUtil {
        static inline bool isEndOfFileToken(TokenBase *token) {
            return token != nullptr
                   && token->parentNode != nullptr
                   && ((NodeBase*)(token->parentNode))->vtable->nodeTypeId == NodeTypeId::EndOfDoc;

        }
    };

    // Tokenizer functions for different nodes and tokens, they will be called in Scanner::scanWithTokenizer, and they will try to match the text with corresponding node/token, if matched, they will generate the node/token and return the position after the matched text, otherwise they will return Search::NOTFOUND.
    struct Tokenizers {
        // Tokens
        static int identifierTokenizer(TokenizerParams_argNode_ch_start_context);
        static int stringLiteralTokenizer(TokenizerParams_argNode_ch_start_context);

        // Nodes
        static int classTokenizer(TokenizerParams_argNode_ch_start_context);
        static int tokenizeExpression(TokenizerParams_argNode_ch_start_context);
        static int typeTokenizer(TokenizerParams_argNode_ch_start_context);

        static int fixedLiteralNodeTokenizer(TokenizerParams_argNode_ch_start_context);
        static int numberNodeTokenizer(TokenizerParams_argNode_ch_start_context);

        static int bodyTokenizer(TokenizerParams_argNode_ch_start_context);
        static int fnTokenizer(TokenizerParams_argNode_ch_start_context);

        static int tokenizeAssignment(TokenizerParams_argNode_ch_start_context);
        static int assignmentWithoutTypeTokenizer(TokenizerParams_argNode_ch_start_context);
        static int tokenizeExpressionFirstAssignment(TokenizerParams_argNode_ch_start_context);

        static int returnStatementTokenizer(TokenizerParams_argNode_ch_start_context);
        static int parenthesesTokenizer(TokenizerParams_argNode_ch_start_context);
        static int identifiersAccessTokenizer(TokenizerParams_argNode_ch_start_context);

        static int tokenizeFuncCall(TokenizerParams_argNode_ch_start_context);
        static int binaryOperationTokenizer(TokenizerParams_argNode_ch_start_context);

        // tokenizer for simple keywords or symbols, like "null", "true", "false", " ", etc... they can be tokenized in one step without backtracking, so we can use this template function to generate them.
        // generator is a function pointer for generating corresponding token, it will be called when the word is matched, and the generated token will be returned by the tokenizer.
        template<typename TYPE, std::size_t SIZE, typename GENTYPE>
        static inline int tokenizeWord(TokenizerParams_argNode_ch_start_context
                      , GENTYPE* (*generator)(ParseContext *, NodeBase*)
                      , utf8byte capitalLetter
                      , const TYPE(&word)[SIZE])
        {
            if (capitalLetter == ch) {
                int length = st_size_of(word) - 1;
                if (ParseUtil::matchWordWithTerminatableEnd(context->chars, context->length, start, word)) {
                    auto *token = (SimpleTextTokenStruct*)(generator(context, Cast::downcast<NodeBase*>(argNode)));

                    token->foundPos = start;
                    token->text = context->memBuffer.newText(length);
                    token->textLength = length;

                    TEXT_MEMCPY(token->text, context->chars + start, length);
                    token->text[length] = '\0';

                    context->mostLeftToken = Cast::upcastToken(token);
                    return start + length;
                }
            }

            return Search::NOTFOUND;
        }

        // SimpleTextNodeStruct
        template<typename TYPE, std::size_t SIZE>
        static inline int WordTokenizer(TokenizerParams_argNode_ch_start_context
                , utf8byte capitalLetter
                , const TYPE(&word)[SIZE])
        {
            return tokenizeWord(TokenizerParams_pass, Alloc::newSimpleTextToken, capitalLetter, word);
        }
    };


    /**
     * Implements common scanning and parsing method
     */
    struct Scanner {
        static int scanRoot(void *parentNode, TokenizerFunction tokenizer, ParseContext *context);

        static int scanOnce(void *parentNode, TokenizerFunction tokenizer, ParseContext *context, int start);

        static int scanLoop(void *parentNode, TokenizerFunction tokenizer, ParseContext *context, int start);
    };
}